### PR TITLE
fix bug in filling weighted count histogram

### PR DESCRIPTION
**Pull request by AndrewLevin**
The weighted histogram should be filled with a negative weight in the same bin.

### CODE REVIEW

**Comment by arizzi** [comment]
well it is commented out code and it really depends on what you want to count... counting individually positive and negatives may have adavantages

**Comment by AndrewLevin** [comment]
I just pushed a commit which uncomments the filling of the weighted histogram and automatically detects when there is a generator weight. I think it makes more sense to fill the positive and negative weights in a single bin, since the sum of them is what people typically want, and you can recover the separate numbers by combining with the unweighted number of events histogram.

**Comment by arizzi** [comment]
I think changing something that other people may already be using would need a stronger reason.
Given that all representations allow to recover one or another number, I would prefer not to change the meaning.

**Comment by AndrewLevin** [comment]
Well, currently, it fills a histogram with a range from 0 to 1 at -0.5. I think it is probably more likely that someone is using it incorrectly now i.e. using the bin 0 to 1 as if it had both positive and negative weights.

**Comment by arizzi** [comment]
ok let's change the name then to "nEventsGenWeighted"

**Comment by arizzi** [comment]
I mean so that if anyone was using the old one we do not break the interface

**Comment by AndrewLevin** [comment]
ok, how about this? I changed the name to `nEventsGenWeighted` and added back the old histogram commented like it was before.

**Pull request merged**
