### PR TITLE
Python3 support (#1)

### PR DESCRIPTION
**Pull request by Laurits7**
Python3 support and pep8.

### CODE REVIEW

**Comment by Laurits7** [comment]
Regarding issue #246

**Comment by Laurits7** [comment]
pylint: fixed some bug not related to Python2 -> Python3. Regarding commit 6c19200

**Comment by mariadalfonso** [comment]
@Laurits7 
could you please rebase this PR ? we have conflicts

**Comment by Laurits7** [comment]
Yes, thanks for reminding! Will update the PR when done

**Comment by gouskos** [comment]
Hi @Laurits7 ; Why did you close the PR? :)
I just did a very quick test and seems to run fine and I was about to merge it

**Comment by Laurits7** [comment]
Sorry, was not on purpose. Shall I open a new one or can this be reopened?

**Comment by gouskos** [comment]
I cannot reopen it. Can you please submit a new one and we will merge it. thank you.

**Pull request closed without merging**
