### PR TITLE
Added JMS and JMR sf for FatJet for 2018 in jetmetHelper

### PR DESCRIPTION
**Pull request by valsdav**
Updated 2018 JMS and JMR scale factors for FatJets from https://twiki.cern.ch/twiki/bin/view/CMS/JetWtagging

### CODE REVIEW

**Comment by fgolf** [comment]
The proposed changes are ok, but before merging them I'd like to understand why the numbers in fatJetUncertainties.py and jetmetHelperRun2.py.  Should they be the same?

**Comment by valsdav** [comment]
Hi, thanks for your comment. 
As far as I have understood the numbers in jetmetHelperRun2 correspond to tau21<0.45 HP category official WP, whereas the ones inside the fatJetUncertainty module correspond to the tau21DDT working point. 

I agree that this could be refactored to save both in the jetmethelper for clarity.

**Comment by fgolf** [comment]
@camclean Can you take a look at comment on this?  Thanks.

**Comment by camclean** [comment]
"As far as I have understood the numbers in jetmetHelperRun2 correspond to tau21<0.45 HP category official WP, whereas the ones inside the fatJetUncertainty module correspond to the tau21DDT working point."
>> This is correct. The numbers look right.

It would indeed be nice to refactor the modules so that the values were all in the jetmethelper.

**Comment by fgolf** [comment]
Thanks @camclean.  I'll merge this and open an issue to factorize the remaining values into jetmethelper.

**Pull request merged**
