### PR TITLE
Do JEC before smearing

### PR DESCRIPTION
**Pull request by camclean**
Added latest jer/jec text files. Also edited jme modules to have correct list of uncertainty sources, redo jec before smearing, apply jec to both mass and pt, and have raw mass/pt branches and smearing uncertainty branches. Note: Jet and FatJet raw mass/pt branches will be empty if that branch does not have the rawFactor attribute.

### CODE REVIEW

**Comment by arizzi** [comment]
can I close this one?

**Comment by camclean** [comment]
No, the jer corrections should be done after the jecs are redone. Also, the jecs should be applied to both pT *and* mass. Saving the raw, uncorrected, values of pT and mass are also desirable. I can open a ticket if you like.

**Comment by arizzi** [comment]
it seems there are some conflict.
are the  txt files updated to latest calibrations?
I thought some of them were already push by other PRs

@rappoccio can you comment on the proposed code changes?

**Comment by rappoccio** [comment]
This is an expected update, we need to switch the order of the JEC and JER applications. It now needs rebasing, though.

**Comment by camclean** [comment]
What's the status of this PR? Is there something else I need to do?

**Comment by arizzi** [comment]
can you rebase and solve conflicts?

**Comment by arizzi** [comment]
@rappoccio can anyone provide a minimal fix on current master of the JEC / JER order issue? This PR is not really minimal.

**Comment by rappoccio** [comment]
Yes, we can do that tomorrow, Christine is training today.

**Comment by arizzi** [comment]
any update?

**Comment by camclean** [comment]
Unfortunately you asked at a very busy time. I am working on it as quickly as my schedule allows.

**Comment by arizzi** [comment]
@rappoccio one question: if the JEC one applies in postprocessing are the same already applied in the production of nanoaod, is the output of the current module correct (i.e. the JEC/JER order doesn't matter) ?

**Comment by rappoccio** [comment]
@arizzi I think in that case it should indeed not matter (although I could be thinking about this wrong).

**Comment by camclean** [comment]
@arizzi The order only matters if you re-apply the JEC. In that case, it matters even if you do not change JEC versions.

**Comment by camclean** [comment]
@arizzi I am closing this PR and opening a new one that has fewer changes.

**Pull request closed without merging**
