### PR TITLE
Ultra legacy PU histograms and PU weight producers

### PR DESCRIPTION
**Pull request by danbarto**
Updated and added the UL pileup histograms for MC and data, all expanded to 100 bins, and corresponding PU weight producers.

The MC histograms were extracted from:
- UL 2016: https://github.com/cms-sw/cmssw/blob/master/SimGeneral/MixingModule/python/mix_2016_25ns_UltraLegacy_PoissonOOTPU_cfi.py
- UL 2017: https://github.com/cms-sw/cmssw/blob/master/SimGeneral/MixingModule/python/mix_2017_25ns_UltraLegacy_PoissonOOTPU_cfi.py
- UL 2018: https://github.com/cms-sw/cmssw/blob/master/SimGeneral/MixingModule/python/mix_2018_25ns_UltraLegacy_PoissonOOTPU_cfi.py

Data histograms are taken from `/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions1*/13TeV/PileUp/UltraLegacy/`, following the hypernews post here: https://hypernews.cern.ch/HyperNews/CMS/get/physics-validation/3709.html

### CODE REVIEW

**Comment by mariadalfonso** [comment]
@danbarto 
see slide 9 https://indico.cern.ch/event/1039035/contributions/4403398/attachments/2265302/3846186/pileup-xpog-2021-06-16.pdf

the histogram should be already centrally distrubuted
/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions18/13TeV/PileUp/UltraLegacy/
What about using these instead of creating new ones ?

**Comment by danbarto** [comment]
The data PU distributions are essentially the ones from the path you pointed to, combined into a single file with central, up and down so that the existing PU weight producer can read it properly. Additionally, the afs directory isn't mounted everywhere, so I think adding the files to the repository makes sense.

In the end, if there's a better (central?) solution, I'm happy to use it. I just collected all the histograms needed for doing proper PU reweighting with UL samples, and thought it could be useful for others, too.

**Comment by gouskos** [comment]
Hi @danbarto @mariadalfonso Looks fine to me. 
On the very near term future we should migrate the functions t https://github.com/cms-nanoAOD/correctionlib [decoupled from CMSSW] and store files in cvmfs.

**Comment by mariadalfonso** [comment]
@danbarto
we will merge your addition.

In the future all the external inputs should move to the central json files
https://gitlab.cern.ch/cms-nanoAOD/jsonpog-integration

here the library to read them https://github.com/cms-nanoAOD/correctionlib

**Pull request merged**
