### PR TITLE
Recompute existing branches

### PR DESCRIPTION
**Pull request by lenzip**
In case one adds a branch that was already there, the existing branch is first scratched from the output tree and the new one is then added.

### CODE REVIEW

**Comment by lenzip** [comment]
this has a problem. In case more modules are run in the same loop, the second still sees the original branch

**Comment by lenzip** [comment]
I take my previous comment back. This modification actually works even when multiple modules are run in the same loop, provided the modified is accessed from python (when I wrote my earlier comment I was actually using a TTreeFormula, which of course only knows the branches in the input tree). However, uponUpdating the branch, it is propagated to the inputTree with the extraBranch mechanism of InputTree class. Thus when the next module accesses the input tree, if I understand correctly the logic, the modified branch takes precedence on the original one upon calling InputTree.readBranch [(here)](https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/python/postprocessing/framework/treeReaderArrayTools.py#L51).

**Comment by lenzip** [comment]
Is there anything pending preventing the merge of this pull request?

**Comment by arizzi** [comment]
I guess not, but I did not test it myself. unless @gpetruc or others have objections I'd merge

**Pull request merged**
