### PR TITLE
Updating JECs, and adding an HT module

### PR DESCRIPTION
**Pull request by rappoccio**
The JECs for the 2016 data were not present. If we want to add the recalibrator, we should add them.

I also added an HT module, seems useful. 

(EDIT: I meant 2016 data)

### CODE REVIEW

**Comment by arizzi** [comment]
I see already some 
Fall17_17Nov2017B_V6_DATA 
aren't these more up to date than the one you posted?

concerning HT I think we had an existing module from day zero that included also lepton cleaning

**Comment by arizzi** [comment]
ah sorry it was an MHT calculator

**Comment by arizzi** [comment]
is this still relevant or can it be closed?

**Comment by rappoccio** [comment]
This is still needed for the HT producer. @camclean are the txt files obsolete or are they still needed here?

**Comment by camclean** [comment]
The 2017 text files are up to date. The 2016 text files are the most recent ones not affected by the formula evaluator bug, so I think we should keep them. 

Next, I can add the 2018 and most recent, but buggy, 2016 text files. Though I think that should be in a later PR.

**Comment by fgolf** [comment]
@rappoccio 

Sorry this has languished, getting back to it now.  The JEC updates were merged as part of PR #133, but it would be good to add the HT module.

As there have been a number of changes since this PR was made, only 3 of the files are needed so I thought it would be easier to make a new PR, #157 does this.  Ran basic tests and everything looks as expected.  If you're ok with this, I'll go ahead and merge it.

Thanks and sorry again for this sitting for so long.

**Comment by fgolf** [comment]
closing, superseded by #157

**Pull request closed without merging**
