### PR TITLE
Update JECs, JMS/JMR values, and add PUPPI SD mass correction

### PR DESCRIPTION
**Pull request by lcorcodilos**
Apologies that this is all coming in one PR. Doing several separate small PRs and then trying to merge or rebase for each that was approved seemed like an unnecessary hassle when there's a lot of overlap here.

- Moved old JEC/JER archive files to OldArchives/ to keep them from being confused with what's being currently used (I can just delete this if we want).
- Fixed issue #155 by adding and switching to Summer16_07Aug2017_V11_MC.
- Removed hard coded strings that now reference the global tag instead.
- Flipped up and down values in self.jmsVals for consistency with everything else.
- Fixed issue #150 by adding new JMR values for 2016 and 2017 (2018 uses 2017 values).
--- This should be checked by an expert. I believe the values should just be those listed [here](https://twiki.cern.ch/twiki/bin/view/CMS/JetWtagging) with no alteration.
- Fixed issue #151 by adding new JMS values for 2016 and 2017 (2018 uses 2017 values).
- Fixed issue #156 by applying the PUPPI SD mass correction before JMS and JMR corrections but after the JECs (was not applied at all before). 
--- Added corresponding file puppiCorr.root from [1].
--- Added branch to save the correction.
- Defined the missing jet_m_resolution variable described in issue #161 using the recipe from [here](https://twiki.cern.ch/twiki/bin/view/Sandbox/PUPPIJetMassScaleAndResolution#PUPPI_softdrop_mass_resolution).
--- Added corresponding file puppiSoftdropResol.root from [1].

[1] - https://github.com/cms-jet/PuppiSoftdropMassCorr/tree/master/weights

@camclean @pmaksim1

### CODE REVIEW

**Comment by lcorcodilos** [comment]
It seems I made a mess of this. I'm cancelling this PR, deleting the branch, and starting over once PR #160 is merged.

**Comment by davignon** [comment]
@lcorcodilos 
In the end did you make a PR that solved issue #161 ?
Thanks a lot!

**Comment by camclean** [comment]
Should be PR #166

**Comment by davignon** [comment]
Thanks @camclean , I'll ask for it to be reviewed and merged. Issue #161 is currently blocking us.

**Pull request closed without merging**
