### PR TITLE
Add statusflag help function to Object class

### PR DESCRIPTION
**Pull request by IzaakWN**
This small class method would help simplify some code and make it more readable:
```
for part in Collection(event,'GenPart'):
  isPrompt = part.statusflag('isPrompt')
  isPromptHard = part.statusflag('isPrompt','fromHardProcess')
  # ...
```
I left the `statusflags` dictionary global in `datamodel.py` so the user can still update the dictionary if needed in the future, or import it for some other purpose
```
import PhysicsTools.NanoAODTools.postprocessing.framework.datamodel as datamodel
datamodel.statusflags['fromHardProcess'] = 8
datamodel.statusflags['hard'] = 8 # shorthand
```

### CODE REVIEW

**Comment by clelange** [comment]
Let's actually get back to this. In https://github.com/cms-sw/cmssw/pull/42323#issuecomment-1663492639 it was pointed out that this could be useful. @IzaakWN would you mind having another look whether this is still up-to-date and working with the latest NanoAOD version and then we could merge it?

**Comment by IzaakWN** [comment]
Hi @clelange, thanks for coming back to this!

The status flag dictionary is still up to date, and I added this link to the code for future reference:
https://github.com/cms-sw/cmssw/edit/master/PhysicsTools/NanoAOD/python/genparticles_cff.py

I also validated with UL2018 v9:
```
mkdir -p test; cd test
source $VO_CMS_SW_DIR/cmsset_default.sh
export CMSSW=CMSSW_12_4_8
export SCRAM_ARCH=slc7_amd64_gcc10
cmsrel $CMSSW
cd $CMSSW/src
git clone -b addStatusFlags git@github.com:IzaakWN/nanoAOD-tools.git PhysicsTools/NanoAODTools
cd PhysicsTools/NanoAODTools
cmsenv
scram b -j8
```
And I have validated the code with the following LHE gen dumper script, which I added as an example to this PR for other analyzers:
```
python3 python/postprocessing/examples/exampleGenDump.py -i root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/280000/525CD279-3344-6043-98B9-2EA8A96623E4.root
python3 python/postprocessing/examples/exampleGenDump.py -i root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/130000/44187D37-0301-3942-A6F7-C723E9F4813D.root
```
Attached are the printout of both these commands:
* [genDumper_DYJetsToLL.txt](https://github.com/cms-nanoAOD/nanoAOD-tools/files/12289694/genDumper_DYJetsToLL.txt)
* [genDumper_TTTo2L2Nu.txt](https://github.com/cms-nanoAOD/nanoAOD-tools/files/12289695/genDumper_TTTo2L2Nu.txt)

As an example, this is the printout for one of the Z → 𝜏𝜏 events:
```
–––––––––– Event 14580006 ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
   index   pdgId    moth  mothId      dR      pt     eta  status   prompt  taudecay  last copy  
       0      -5                            0.00  999.00      21     True     False       True
       1       5                            0.00 -999.00      21     True     False       True
       2      23       0      -5    0.00    0.00  999.00      22     True     False      False
       3      23       2      23  999.00    7.16    2.80      44     True     False      False
       4      23       3      23    1.29    3.22    3.55      44     True     False      False
       5      23       4      23    0.89    5.50    3.02      44     True     False      False
       6      23       5      23    0.14    5.08    3.10      44     True     False      False
       7      23       6      23    0.45    4.38    3.25      62     True     False       True
       8     -15       7      23    2.56   46.88    0.74       2     True     False       True
       9      15       7      23    3.83   43.12    0.42       2     True     False       True
      10     523                            9.50   -0.49       2     True     False       True
      11    -523                            4.86    3.44       2     True     False       True
      12     -16       8     -15    0.08    8.50    0.67       1    False      True       True
      13     -13       8     -15    0.02   31.31    0.76       1    False      True       True
      14      14       8     -15    0.01    7.06    0.74       1    False      True       True
      15      16       9      15    0.04   14.97    0.41       1    False      True       True
      16     111       9      15    0.02    8.19    0.44       2    False      True       True
      17     111       9      15    0.13    1.22    0.30       2    False      True       True
      18    -211       9      15    0.02   18.75    0.42       1    False      True       True
      19     521      10     523    0.00    9.41   -0.48       2    False     False       True
      20    -521      11    -523    0.01    4.88    3.43       2    False     False       True
      21      22      16     111    0.01    6.88    0.44       1    False      True       True
      22      22      16     111    0.03    1.32    0.42       1    False      True       True
      23      22      17     111    0.16    0.39    0.17       1    False      True       True
      24      22      17     111    0.08    0.84    0.36       1    False      True       True
      25      14      19     521    0.88    1.33   -0.54       1    False     False       True
      26     -13      19     521    1.36    0.54    0.86       1    False     False       True
      27    -423      19     521    0.15    8.12   -0.53       2    False     False       True
      28    -433      20    -521    0.68    1.47    3.22       2    False     False       True
      29     423      20    -521    0.24    3.80    3.40       2    False     False       True
      30    -421      27    -423    0.02    7.92   -0.54       2    False     False       True
      31    -431      28    -433    0.10    1.31    3.30       2    False     False       True
      32     421      29     423    0.02    3.73    3.39       2    False     False       True
      33      11      30    -421    0.23    2.37   -0.55       1    False     False       True
      34     -12      30    -421    1.14    0.10    0.60       1    False     False       True
Boson production:
 -5 –>  23 –>  23 –>  23 –>  23 –>  23 –>  23 –> -15
                                              –>  15
Tau decay:
-15 –> -16
    –> -13
    –>  14
Tau decay:
 15 –>  16
    –> 111 –>  22
           –>  22
    –> 111 –>  22
           –>  22
    –> -211
```

The only thing I have not tested is the performance of the `Object.statusflag` method compared to actually doing the bitwise operation yourself without a lookup, but that's up to analyzers, and I think this implementation provides a nice example.

If you have no further comments, this PR is ready to merge from my side.

**Comment by IzaakWN** [comment]
Validated in python2:
```
mkdir -p test; cd test
source $VO_CMS_SW_DIR/cmsset_default.sh
export CMSSW=CMSSW_11_2_5
export SCRAM_ARCH= slc7_amd64_gcc900
cmsrel $CMSSW
cd $CMSSW/src
git clone -b addStatusFlags git@github.com:IzaakWN/nanoAOD-tools.git PhysicsTools/NanoAODTools
cmsenv
scram b -j8
cd PhysicsTools/NanoAODTools/

python/postprocessing/examples/exampleGenDump.py -i root://xrootd-cms.infn.it//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/70000/2D494ABA-4415-6246-8136-C48D11A2F80B.root
```
Had to add changes to `exampleGenDump.py` to make it work: `len(particles)` → `particles._len`, see https://github.com/cms-nanoAOD/nanoAOD-tools/pull/307#issuecomment-1669957997.

**Comment by namapane** [comment]
Hi @IzaakWN , please note that while importing this into the CMSSW PR (see above) I:
- moved exampleGenDump.py to test, as done for other examples
- moved the hasbit helper into the example as tools.py was not imported in the package (all functions it contains are already existing elsewhere in CMSSW)
BTW comments on this PR are welcome, especially if you are interested in using it in standalone mode (outside CMSSW).

**Pull request merged**
