### PR TITLE
Updated to use latest JME corrections

### PR DESCRIPTION
**Pull request by camclean**
Updated correction values:
- JMS and JMR SFs now reflect W-tagging recommendations. (Addresses issues #150 and #151.)
- Now using latest 2016 MC JECs to address issue #155.

Added raw and jec correction branches to data (to be consistent with MC) and option to redoJEC (or not) to address issue #158.

### CODE REVIEW

**Comment by camclean** [comment]
@arizzi @fgolf - are there any problems merging this request?

**Comment by arizzi** [comment]
I let @fgolf comment as he is taking responsibility for nanoaod-tools updates

**Comment by arizzi** [comment]
btw what is the interplay with #163

**Comment by lcorcodilos** [comment]
My fault actually - I just started changing things that I saw were incorrect and it wasn't until I submitted the PR that I started linking my fixes with the issues that @camclean posted. I missed this PR so there's overlap. I'll compare the two and remove what's redundant from mine.

**Comment by lcorcodilos** [comment]
Actually, what's the cleanest/simplest thing to do here? I need to adapt the code from #163 to the code here. I think it makes the most sense to wait for this PR to merge into cms-nanoAOD, merge cms-nanoAOD/master into my fork, and then commit the merge to my fork. I think #163 should update automatically and then only have my relevant changes.

**Comment by fgolf** [comment]
The proposed changes look ok, but I have a question about the scope.  It looks like the updated JMR scale factors come from W-tagging studies, are they also recommended only for a particular use case or generally for other uses and jet types?

**Comment by camclean** [comment]
@fgolf this is a question I plan to discuss at the jetmet meeting tomorrow. It may make more sense to add an option to apply jet mass smearing or not. Either way, the values currently in use are definitely wrong.

**Comment by lcorcodilos** [comment]
@fgolf The discussion today at the JetMET meeting concluded that an option should be added eventually but that a user can factorize what they need with the current setup by taking the raw values and applying each of the saved corrections. 

Once this is merged, I'll submit a new PR with the PUPPI SD mass correction implemented.

**Pull request merged**
