### PR TITLE
Update JECs and scripts for 2017 and preliminary 2018

### PR DESCRIPTION
**Pull request by lcorcodilos**
Hi all,

Based on my reading of https://twiki.cern.ch/twiki/bin/view/CMS/JECDataMC, it seems that the jetmetUncertainties.py and jetRecalib.py modules are out of date. This PR should ammend the scripts and add the new JEC/R files to /data/jme/. I think there's an argument for removing the old txt files to avoid confusion and keep the repo cleaner but there may be a reason to keep them that I haven't thought so I've left them for now.

This is my first time having to handle these so please double check my work :-)

In particular, I'm not sure why redoJEC=True for jetmetUncertainties2017All. I've set it to False for 2018 but that was just a guess.

Additionally, I came across an issue that noGroom=True does not work for any year. All of the msoftdrop branches generated in jetmetUncertainties.py are filled with -1. Through some print outs, I traced this back to the [genJets and subGenJets collections](https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/python/postprocessing/modules/jme/jetmetUncertainties.py#L161-L162) being empty. I downloaded a central NanoAOD file to confirm that this is NOT true and tested to see that this is not unique to the PR code. I didn't dig into this further since it's clear that my code didn't cause (or solve) the issue but I figure it's worth mentioning. If someone has a fix, I can implement it in this PR.

Lucas

### CODE REVIEW

**Comment by lcorcodilos** [comment]
Some of my changes are identical to what was proposed in #113 but mine include 2018 values, a fix to issue #98, and updates to jetRecalib.py

**Comment by arizzi** [comment]
@kschweiger @ashrafkasem can you cross check and comment?

**Comment by lcorcodilos** [comment]
Adding @pmaksim1

**Comment by lcorcodilos** [comment]
Also adding @rappoccio @UBParker. I'd add Christine as well but I can't find her

**Comment by lcorcodilos** [comment]
Sorry - clicked the wrong button!

**Comment by arizzi** [comment]
I think there are way too many files pulled in by this PR, do we really need JECs for each separate run period? I guess not.
I would also suggest that for better handling of so many conditions we create a tgz file for each relevant GT and we unpack it on the fly when running, or  something like it.

Can you separate the fixes in the py code from the update of the txt files in two PRs so that the code is actually reviwable ?

**Comment by rappoccio** [comment]
> I think there are way too many files pulled in by this PR, do we really need JECs for each separate run period? I guess not.

We do, unfortunately. This complication is the primary reason I'm not thrilled about the re-application of JECs at the NANOAOD level. It seems to be popular instead of just remaking them as soon as new JECs come out, so here we are. 

> I would also suggest that for better handling of so many conditions we create a tgz file for each relevant GT and we unpack it on the fly when running, or something like it.
> 

That may be a wiser choice, I agree. 

> Can you separate the fixes in the py code from the update of the txt files in two PRs so that the code is actually reviwable ?

Also +1 for this.

**Comment by lcorcodilos** [comment]
I also just noticed that a commit from October sneaked in here.

So here's my plan then. I'll separate my fork into three branches and revert them all back to the original fork state. Then each fork will have a single commit 
- One for the python module changes. I'll put something in the module to untar in `__init__` and delete the untarred folder in `endJob`(?)
- One for the JECs which I'll tar together 
- One for my stray commit to treeReaderArrayTools.py

Then we can close this PR and start from those.

**Comment by lcorcodilos** [comment]
I have a follow up coding question to this. I was looking into good ways to access tgz contents and came across `tarfile` in python. 

We can do something like 
`import tarfile`
`self.tar = tarfile.open(globalTag + '.tgz', 'r:gz')`
`with self.tar.extractfile(self.jesUncertaintyInputFileName) as f:`
`    ....`

and now `f` can be used as normal but we never extract the txt file permanently in any directory (so there's no cleanup). Sound reasonable?

**Comment by lcorcodilos** [comment]
It's occurred to me that this won't work with `JetCorrectorParameters` because that requires a string input so I'll instead use `tarfile.extractall()` to a get everything in a scratch directory that gets tossed at the end.

**Comment by lcorcodilos** [comment]
New PRs created. I think it's safe to close this one now.

**Comment by lcorcodilos** [comment]
Just wanted to leave a comment about the "noGroom=True does not work for any year" issue I originally commented on. The fault was on my end - one needs to make sure that GenJets is "kept" in the keep and drop file so that the module can access it.

**Pull request closed without merging**
