### PR TITLE
Updates on T1Smear MET calculation: Central value + JME uncertainties

### PR DESCRIPTION
**Pull request by alpakpinar**
This PR contains new code that has:

- Separate calculations of JME uncertainties for T1 and T1Smear MET, which are stored in different branches
- An option flag in jetmetHelper to specify which MET uncertainties (T1 or T1Smear) are to be saved

### CODE REVIEW

**Comment by ahinzmann** [comment]
How about making this a bit flexible and allow to save T1 T1smear or both uncertainties, rather than switching with an XOR "useT1SmearMETforUncs"? This would easy analyzers to compare the two METs with corresponding uncertainties if needed.

**Comment by alpakpinar** [comment]
Hi @ahinzmann , I just made a quick update regarding your comment. Instead of the old "useT1SmearMETforUncs" flag, I added a parameter saveMETUncs, in which one can specify a list of MET uncertainties to be saved. The parameter enters in the jetmetHelperRun2 script in [1].

With this setup, one can save both T1 and T1Smear uncertainties (default for now, but we can maybe update), or just save one of them. Do you think this new uncertainty flag will work? Thanks!

[1]: https://github.com/alpakpinar/nanoAOD-tools/blob/2020-07-01_met_fixes/python/postprocessing/modules/jme/jetmetHelperRun2.py#L60

**Comment by mariadalfonso** [comment]
@alpakpinar
we have conflict in this PR since other two were merged, can you rebase ?

**Comment by alpakpinar** [comment]
Hi @mariadalfonso , thanks for notifying me, I'm working on it.

**Comment by gouskos** [comment]
Hi @alpakpinar a gentle ping concerning this PR. Thanks!

**Comment by alpakpinar** [comment]
Hi @gouskos , sorry for the delay. I now completed rebasing against the current master branch. I tested running the updated JME module on some small ntuples and I didn't encounter a problem. Let me know if you want any modifications and I can work on them, thank you!

**Comment by gouskos** [comment]
Thank you @alpakpinar . We will merge this PR now, and we will come back to you [and JME conveners] for suggestions on the tool.

**Comment by alpakpinar** [comment]
Sounds good, thanks a lot @gouskos!

**Pull request merged**
