### PR TITLE
Systematic uncertainty on corrected muon momentum

### PR DESCRIPTION
**Pull request by HeinerTholen**
Systematic uncertainty for muons.

### CODE REVIEW

**Comment by HeinerTholen** [comment]
I don't quite see why there are conflict. My new version should superseed whatever was there before.

**Comment by arizzi** [comment]
you made a pull request to central nanoAOD-tools repository... not the vhbb one. 
If that's what you meant please give a better description than "V5"

**Comment by arizzi** [comment]
concerning the conflicts, someone must have modified the same file so I'm not sure how github (or you :-) ) can tell that your new version should superseed whatever was there before...

**Comment by HeinerTholen** [comment]
This PR is indeed intendet for cms-nanoAOD, sorry for the crappy title that I made at first. 

Not sure what I could do to make it mergeable. It says "Only those with write access to this repository can merge pull requests."  ...

**Comment by arizzi** [comment]
this is including #89 right?

**Comment by HeinerTholen** [comment]
Not sure what you mean, but the change from #89 is still present in the master branch now.

**Comment by arizzi** [comment]
it is because I just merged yours :-)

**Pull request merged**
