### PR TITLE
Add tau correction module, tool and data files

### PR DESCRIPTION
**Pull request by IzaakWN**
Add nanoAOD module `tauCorrProducer.py`, which adds branches with tau ID SFs and applies the tau energy scale to the tau mass and pT. It makes use the official TauPOG tool `TauIDSFTool.py` (in `python/postprocessing/helpers/`), and tau files (in `python/postprocessing/data/tau`). The tool and files are take directly from [`cms-tau-pog/TauIDSFs`](https://github.com/cms-tau-pog/TauIDSFs). Added files:
- `python/postprocessing/modules/common/tauCorrProducer.py`
- `python/postprocessing/helpers/TauIDSFTool`
- `python/postprocessing/data/tau/*.root`

It can be used in post-processing for example as follows:
```
from PhysicsTools.NanoAODTools.postprocessing.modules.common.tauCorrProducer import TauCorrectionsProducer
campaign = '2018ReReco'
module2run = lambda: TauCorrectionsProducer(campaign)
p = PostProcessor('.',infiles,None,noOut=False,modules=[module2run()])
```

Furthermore, some help functions are added to `tools.py` to help with opening files (`ensureTFile`) and extracting histograms (`extractTH1`).

### CODE REVIEW

**Comment by hqucms** [comment]
The changes brought by this PR is not python3 compliant, e.g., https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/python/postprocessing/helpers/tauTriggerSFTool.py#L31

**Comment by mariadalfonso** [comment]
> The changes brought by this PR is not python3 compliant, e.g., https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/python/postprocessing/helpers/tauTriggerSFTool.py#L31

@IzaakWN can you propose a fix ?

**Comment by IzaakWN** [comment]
Thanks for pointing this out, @hqucms. It seems like `nanoAOD-tools` was made python3 compatible before the implementation of this PR. Did it break other things, or were you just not able to use `TauTriggerSFTool`?

**Comment by mariadalfonso** [comment]
@hqucms can you check the proposed fix solve the problem you observe ?
let us know, so that we can merge the PR

**Comment by hqucms** [comment]
@mariadalfonso Yes the problem is fixed for me after merging https://github.com/cms-nanoAOD/nanoAOD-tools/pull/268. 
Thank you very much for the prompt fix, @IzaakWN !

**Pull request merged**
